services:
  app:
    build: .
    container_name: digitalstrides-app
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - SMTP_USER=nico.becker@digitalstrides.de
      - SMTP_PASS=Bw/%/T2rL93WFP5
